name: Multi-Platform Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - '2.6 webapp（流式传输测试版）/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 QEMU 用于多架构仿真
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          version: v1.14.0  # 使用稳定版本
          driver: docker-container
          buildkitd-flags: --debug

      # 登录到 GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 转换为小写仓库名
      - name: Convert repository to lowercase
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$LOWERCASE_REPO" >> $GITHUB_ENV

      # 多平台构建和推送
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./2.6 webapp（流式传输测试版）
          file: ./2.6 webapp（流式传输测试版）/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:2.6
            ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false  # 禁用证明生成以避免之前的错误

      # 添加多架构徽章
      - name: Add multi-arch badge to README
        run: |
          # 创建临时分支
          git checkout -b update-readme-badge
          
          # 更新README
          BADGE_URL="https://img.shields.io/badge/AMD64%20%26%20ARM64-supported-brightgreen"
          if grep -q "multi-arch-badge" README.md; then
            sed -i "s|!\[Multi-Arch Support\].*|![Multi-Arch Support]($BADGE_URL)|" README.md
          else
            echo -e "\n## 🐳 Docker 镜像" >> README.md
            echo "![Multi-Arch Support]($BADGE_URL)" >> README.md
            echo "![Docker Image](https://ghcr-badge.deta.dev/${{ env.REPO_LOWER }}/stock-webapp/latest_tag?trim=major&label=最新版本)" >> README.md
          fi
          
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          git commit -m "Add multi-arch Docker badge"
          
          # 推送到临时分支
          git push origin update-readme-badge
          
          # 创建PR
          gh pr create \
            --title "Update README with multi-arch Docker badge" \
            --body "添加了多架构 Docker 镜像支持徽章" \
            --base main \
            --head update-readme-badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
