name: Build and Push to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - '2.6 webapp（流式传输测试版）/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 关键权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动可用

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./2.6 webapp（流式传输测试版）
          file: ./2.6 webapp（流式传输测试版）/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/stock-webapp:2.6
            ghcr.io/${{ github.repository }}/stock-webapp:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update README badge
        run: |
          echo "![Docker Image]($(ghcr.io/${{ github.repository }}/stock-webapp/badge))" >> README.md
        if: ${{ success() }}
