name: Build and Push to GHCR (Final)
on:
  push:
    branches: [ main ]
    paths:
      - '2.6 webapp（流式传输测试版）/**'
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Convert repository to lowercase
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$LOWERCASE_REPO" >> $GITHUB_ENV
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO_LOWER }}/stock-webapp
          tags: |
            type=raw,value=2.6
            type=raw,value=latest
      
      - name: Build and push Docker image (Multi-architecture)
        uses: docker/build-push-action@v5
        with:
          context: "2.6 webapp（流式传输测试版）"
          file: "2.6 webapp（流式传输测试版）/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Add badge to README
        run: |
          # 创建临时分支
          git checkout -b update-readme-badge
          
          # 更新README
          if grep -q "ghcr-badge.deta.dev" README.md; then
            sed -i 's|!\[Docker Image\].*|![Docker Image](https://ghcr-badge.deta.dev/${{ env.REPO_LOWER }}/stock-webapp/latest_tag?trim=major\&label=最新版本)|' README.md
          else
            echo "![Docker Image](https://ghcr-badge.deta.dev/${{ env.REPO_LOWER }}/stock-webapp/latest_tag?trim=major\&label=最新版本)" >> README.md
          fi
          
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          git commit -m "Update Docker image badge"
          
          # 推送到临时分支
          git push origin update-readme-badge
          
          # 创建PR
          gh pr create \
            --title "Update README with Docker badge" \
            --body "Automatically added Docker image badge to README" \
            --base main \
            --head update-readme-badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
