name: Build and Push to GHCR (Simplified)

on:
  push:
    branches: [ main ]
    paths:
      - '2.6 webapp（流式传输测试版）/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Convert repository to lowercase
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$LOWERCASE_REPO" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          sudo docker build \
            -f "2.6 webapp（流式传输测试版）/Dockerfile" \
            -t ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:2.6 \
            -t ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:latest \
            "2.6 webapp（流式传输测试版）"

      - name: Push Docker image
        run: |
          sudo docker push ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:2.6
          sudo docker push ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:latest

      - name: Add badge to README
        run: |
          echo "![Docker Image](https://ghcr-badge.deta.dev/${{ env.REPO_LOWER }}/stock-webapp/latest_tag?trim=major&label=最新版本)" >> README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          git commit -m "Add Docker image badge" || echo "No changes to commit"
          git push
        if: ${{ success() }}
