name: Build and Push to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - '2.6 webapp（流式传输测试版）/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository to lowercase
        id: lowercase_repo
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$LOWERCASE_REPO" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./2.6 webapp（流式传输测试版）
          file: ./2.6 webapp（流式传输测试版）/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:2.6
            ghcr.io/${{ env.REPO_LOWER }}/stock-webapp:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update README badge
        run: |
          echo "![Docker Image](https://ghcr-badge.deta.dev/${{ env.REPO_LOWER }}/stock-webapp/latest_tag?trim=major&label=最新版本)" >> README.md
        if: ${{ success() }}
